#!/bin/sh
function platform
{       platform=`uname`
        if [ $(uname -p) = 'powerpc' ]; then
        echo "[-] PowerPC is not supported."
        exit 1
        fi
 
        if [ "$platform" = 'Darwin' ]; then
        ADB="adb"
        FASTBOOT="fastboot"
        MD5SUM="md5 -r"
        version="OS X"
        else
        ADB="adb"
        FASTBOOT="fastboot"
        MD5SUM="md5sum"
        version="Linux"
               
        fi
}

platform
	echo "888b     d888          888                              888                8888888888 888                   888      ";
echo "8888b   d8888          888                              888                888        888                   888      ";
echo "88888b.d88888          888                              888                888        888                   888      ";
echo "888Y88888P888  .d88b.  888888  .d88b.  888d888  .d88b.  888  8888b.        8888888    888  8888b.  .d8888b  88888b.  ";
echo "888 Y888P 888 d88\"\"88b 888    d88\"\"88b 888P\"   d88\"\"88b 888     \"88b       888        888     \"88b 88K      888 \"88b ";
echo "888  Y8P  888 888  888 888    888  888 888     888  888 888 .d888888       888        888 .d888888 \"Y8888b. 888  888 ";
echo "888   \"   888 Y88..88P Y88b.  Y88..88P 888     Y88..88P 888 888  888       888        888 888  888      X88 888  888 ";
echo "888       888  \"Y88P\"   \"Y888  \"Y88P\"  888      \"Y88P\"  888 \"Y888888       888        888 \"Y888888  88888P' 888  888 ";
echo "                                                                                                                     ";
    echo "----------------------------------------------------------------------------"
      echo "Bem vindo a ferramente de flash motorola pra linux"
    echo "----------------------------------------------------------------------------"
    		    read \n
getValue(){
	val=$(echo "$1" | sed "s/.*$2=\"\([^\"]*\).*/\1/")
	echo "$val" | grep -q " "
	if [ $? -ne 1 ];then
		val=""
	fi
	echo "$val"
}
PATH=.:$PATH
if hash "$FASTBOOT" 2>/dev/null;then
	cat "$1" | grep step[^s] | while read -r line;do
		MD5=$(getValue "$line" "MD5")
		file=$(getValue "$line" "filename");
		op=$(getValue "$line" "operation");
		part=$(getValue "$line" "partition");
		var=$(getValue "$line" "var");
		if [ "$MD5" != "" ];then
			fileMD5=$($MD5SUM "$file" | sed 's/ \(.*\)//');
			if [ "$MD5" != "$fileMD5" ];then
				echo "$file: MD5 mismatch."
				exit 1;
			fi
		fi
		cmd=$(echo $FASTBOOT "$op" "$part" "$file" "$var" | sed -e 's/[[:space:]]/ /g')
		$cmd
	done
	echo "---------------------------------------------------------"
	echo "Porfavor Verifique os Logs do Seu Dispositivo para verificar se tem algum erro"
	echo "---------------------------------------------------------"
    		    read \n
	$FASTBOOT reboot
else
	echo "FastBoot Não Encontrador Por favor execute o script instalador no Menu"
fi
