#!/bin/sh
function platform
{       platform=`uname`
        if [ $(uname -p) = 'powerpc' ]; then
        echo "[-] PowerPC is not supported."
        exit 1
        fi
 
        if [ "$platform" = 'Darwin' ]; then
        ADB="adb"
        FASTBOOT="fastboot"
        MD5SUM="md5 -r"
        version="OS X"
        else
        ADB="adb"
        FASTBOOT="fastboot"
        MD5SUM="md5sum"
        version="Linux"
               
        fi
}

platform
	echo "    __  ___        __                       __          ______ __              __  ";
echo "   /  |/  /____   / /_ ____   _____ ____   / /____ _   / ____// /____ _ _____ / /_ ";
echo "  / /|_/ // __ \ / __// __ \ / ___// __ \ / // __ \`/  / /_   / // __ \`// ___// __ \";
echo " / /  / // /_/ // /_ / /_/ // /   / /_/ // // /_/ /  / __/  / // /_/ /(__  )/ / / /";
echo "/_/  /_/ \____/ \__/ \____//_/    \____//_/ \__,_/  /_/    /_/ \__,_//____//_/ /_/ ";
echo "                                                                                   ";
    echo "----------------------------------------------------------------------------"
      echo "Bem vindo a ferramente de flash motorola pra linux"
    echo "----------------------------------------------------------------------------"
    		    read \n
getValue(){
	val=$(echo "$1" | sed "s/.*$2=\"\([^\"]*\).*/\1/")
	echo "$val" | grep -q " "
	if [ $? -ne 1 ];then
		val=""
	fi
	echo "$val"
}
PATH=.:$PATH
if hash "$FASTBOOT" 2>/dev/null;then
	cat "$1" | grep step[^s] | while read -r line;do
		MD5=$(getValue "$line" "MD5")
		file=$(getValue "$line" "filename");
		op=$(getValue "$line" "operation");
		part=$(getValue "$line" "partition");
		var=$(getValue "$line" "var");
		if [ "$MD5" != "" ];then
			fileMD5=$($MD5SUM "$file" | sed 's/ \(.*\)//');
			if [ "$MD5" != "$fileMD5" ];then
				echo "$file: MD5 mismatch."
				exit 1;
			fi
		fi
		cmd=$(echo $FASTBOOT "$op" "$part" "$file" "$var" | sed -e 's/[[:space:]]/ /g')
		$cmd
	done
	echo "---------------------------------------------------------"
	echo "Porfavor Verifique os Logs do Seu Dispositivo para verificar se tem algum erro"
	echo "---------------------------------------------------------"
    		    read \n
	$FASTBOOT reboot
else
	echo "FastBoot Não Encontrador Por favor execute o script instalador no Menu"
fi
